//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskServiceAPI.DAL_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string RequestMethod_ { get; set; }
        public string RequestUri_ { get; set; }
        public Nullable<System.DateTime> TimeUtc_ { get; set; }
    }
}
